import ProofProject.Generator

/-!
# Stable semigroups generated by bounded operators

An operator exponential satisfying the required decay bound gives an admissible
semigroup. Its full strong generator graph is exactly the graph of the bounded
operator, so an algebraic two-sided inverse is its generator inverse.
-/

noncomputable section

namespace ProofProject

universe u

variable {H : Type u} [NormedAddCommGroup H] [NormedSpace ℂ H] [CompleteSpace H]

/-- The exponential orbit is differentiable at every real time on a complex
Banach space. No inner product assumption is used. -/
theorem boundedEvolution_hasDerivAt (A : H →L[ℂ] H) (x : H) (t : ℝ) :
    HasDerivAt (fun s : ℝ => NormedSpace.exp ((s : ℂ) • A) x)
      (A (NormedSpace.exp ((t : ℂ) • A) x)) t := by
  have hd := hasDerivAt_exp_smul_const' A t
  have hv := ((ContinuousLinearMap.apply ℂ H x).restrictScalars ℝ).hasFDerivAt.comp_hasDerivAt t hd
  simpa [Complex.coe_smul, Function.comp_def, mul_apply_eq_comp] using hv

/-- The operator exponential, provided with its verified stability bound. -/
def boundedGeneratorSemigroup (M : ℝ) (A : H →L[ℂ] H)
    (hbound : ∀ s : ℝ, 0 ≤ s → ‖NormedSpace.exp ((s : ℂ) • A)‖ ≤ M * Real.exp (-s)) :
    StableSemigroup M H where
  op s := NormedSpace.exp ((s : ℂ) • A)
  at_zero := by simp [ContinuousLinearMap.one_def]
  add s t _ _ := by
    rw [Complex.ofReal_add, add_smul]
    have hc : Commute ((s : ℂ) • A) ((t : ℂ) • A) :=
      ((Commute.refl A).smul_left (s : ℂ)).smul_right (t : ℂ)
    have he := NormedSpace.exp_add_of_commute_of_mem_ball (𝕂 := ℂ) hc
      ((NormedSpace.expSeries_radius_eq_top ℂ (H →L[ℂ] H)).symm ▸ edist_lt_top _ _)
      ((NormedSpace.expSeries_radius_eq_top ℂ (H →L[ℂ] H)).symm ▸ edist_lt_top _ _)
    exact he
  strong_continuous x := by
    exact (continuous_iff_continuousAt.mpr fun t =>
      (boundedEvolution_hasDerivAt A x t).continuousAt).continuousOn
  bound := hbound

@[simp] theorem boundedGeneratorSemigroup_op (M : ℝ) (A : H →L[ℂ] H)
    (hbound : ∀ s : ℝ, 0 ≤ s → ‖NormedSpace.exp ((s : ℂ) • A)‖ ≤ M * Real.exp (-s))
    (s : ℝ) :
    (boundedGeneratorSemigroup M A hbound).op s = NormedSpace.exp ((s : ℂ) • A) := rfl

/-- This identifies the entire right-derivative generator graph. -/
theorem boundedGeneratorSemigroup_generatorGraph (M : ℝ) (A : H →L[ℂ] H)
    (hbound : ∀ s : ℝ, 0 ≤ s → ‖NormedSpace.exp ((s : ℂ) • A)‖ ≤ M * Real.exp (-s))
    (x y : H) :
    GeneratorGraph (boundedGeneratorSemigroup M A hbound) x y ↔ y = A x := by
  have hd : GeneratorGraph (boundedGeneratorSemigroup M A hbound) x (A x) := by
    simpa [GeneratorGraph] using
      (boundedEvolution_hasDerivAt A x 0).hasDerivWithinAt (s := Set.Ici 0)
  constructor
  · intro hy
    exact hy.unique hd
  · rintro rfl
    exact hd

/-- Two algebraic inverse identities imply the actual generator inverse
identity, including every vector in the generator domain. -/
theorem boundedGeneratorSemigroup_isGeneratorInverse (M : ℝ) (A B : H →L[ℂ] H)
    (hbound : ∀ s : ℝ, 0 ≤ s → ‖NormedSpace.exp ((s : ℂ) • A)‖ ≤ M * Real.exp (-s))
    (hAB : A * B = 1) (hBA : B * A = 1) :
    IsGeneratorInverse (boundedGeneratorSemigroup M A hbound) B := by
  intro x y
  rw [boundedGeneratorSemigroup_generatorGraph]
  constructor
  · rintro rfl
    simpa [mul_apply_eq_comp] using congrArg (fun F : H →L[ℂ] H => F x) hBA
  · intro hBy
    have h : A (B y) = y := by
      simpa [mul_apply_eq_comp] using congrArg (fun F : H →L[ℂ] H => F y) hAB
    rw [hBy] at h
    exact h.symm

end ProofProject
