# Generated by the NLA pinned-tool bootstrap.
export PATH=/home/admin/.elan/toolchains/leanprover--lean4---v4.33.1/bin:/home/admin/.elan/bin:/home/admin/mf21-tools/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/snap/bin
export COMPARATOR_BIN=/home/admin/nla-lean-tools/.tools/comparator/.lake/build/bin/comparator
export COMPARATOR_LEAN4EXPORT=/home/admin/nla-lean-tools/.tools/lean4export/.lake/build/bin/lean4export
export COMPARATOR_LANDRUN=/home/admin/nla-lean-tools/scripts/strict_landrun.py
export XDG_CACHE_HOME=/home/admin/nla-lean-tools/.tools/cache
export TMPDIR=/home/admin/nla-lean-tools/.verification-tmp
