"""Independent final-referee source/API/rubric and diagnostic evidence.

The diagnostic is reused from this reviewer's earlier independent statement
review, not from the proof implementer. No candidate source is changed.
"""
from pathlib import Path
import hashlib, json, shutil, subprocess

OUT = Path(__file__).resolve().parent
PROJECT = OUT.parents[1]
REPO = PROJECT.parents[2]
STANDARDS = Path('/tmp/nla-lean-formalization/standards')
PIN = 'afb424eda89e8ac96d9eb69f6a88972055a4cd1b'
sha = lambda p: hashlib.sha256(Path(p).read_bytes()).hexdigest()
save = lambda name, data: (OUT/name).write_text(json.dumps(data, indent=2)+'\n')

commit_path = STANDARDS/'TauCetiProject_TauCetiReview-commit.json'
tree_path = STANDARDS/'TauCetiProject_TauCetiReview-tree.json'
commit = json.loads(commit_path.read_text())
tree = json.loads(tree_path.read_text())
assert commit['sha'] == PIN and not tree['truncated']
# The retained API response was requested by commit and labels its root with
# that request ID. Verify this recorded identity, then each returned blob.
assert tree['sha'] == PIN and tree['url'].endswith('/git/trees/'+PIN)
assert sha(tree_path) == 'c75cbe23de0e71326757d5a83844226409e38451207d108a317cb2c902bf59a6'
blobs = {f['path']: f['sha'] for f in tree['tree'] if f['type']=='blob'}
rubrics = {}
for name in ['correctness', 'scope', 'proof-quality', 'reuse', 'generality',
             'api-design', 'naming', 'placement', 'documentation', 'attribution']:
    rel = 'rubrics/'+name+'.md'
    p = STANDARDS/'sources/TauCetiProject/TauCetiReview'/rel
    raw = p.read_bytes()
    blob = hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()
    assert blob == blobs[rel], rel
    rubrics[rel] = {'sha256': sha(p), 'git_blob_sha1': blob,
                    'url': f'https://github.com/TauCetiProject/TauCetiReview/blob/{PIN}/{rel}'}
save('rubric-inputs.json', {'pin': PIN, 'commit_record_sha256': sha(commit_path),
    'tree_record_sha256': sha(tree_path), 'files': rubrics,
    'local_adaptation': 'docs/lean/REVIEW.md',
    'local_adaptation_sha256': sha(REPO/'docs/lean/REVIEW.md'),
    'scope': 'Independent application of the repository adaptation; not an official Tau Ceti service run.'})

mathlib = PROJECT/'.lake/packages/mathlib'
leancert = PROJECT/'.lake/packages/leancert'
api_files = {
 'Mathlib/Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Abs.lean':
   'Actual square root of star-multiply modulus, positivity, square identity and norm.',
 'Mathlib/Analysis/SpecialFunctions/ContinuousFunctionalCalculus/Rpow/Basic.lean':
   'Uniqueness of actual nonnegative square root (CFC.sqrt_unique).',
 'Mathlib/Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Order.lean':
   'Nonnegative contraction iff order bound by one.',
 'Mathlib/Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Instances.lean':
   'Commute.mul_nonneg genuinely requires and consumes commutation.',
 'Mathlib/Analysis/CStarAlgebra/Matrix.lean':
   'L2 matrix norm bridge to Euclidean CLM and actual diagonal norm.',
 'Mathlib/Analysis/CStarAlgebra/Basic.lean':
   'C-star norm-square identity used for witness operator norm.',
 'Mathlib/RingTheory/RootsOfUnity/Complex.lean':
   'Actual complex exponential primitive root and its unit modulus.',
 'Mathlib/RingTheory/RootsOfUnity/PrimitiveRoots.lean':
   'Geometric sum zero for arbitrary primitive root order greater than one.',
 'Mathlib/Analysis/InnerProductSpace/PiL2.lean':
   'Actual Euclidean norm-square finite sum.',
 'Mathlib/LinearAlgebra/Matrix/PosDef.lean':
   'Gram/outer-product positivity and actual diagonal consequence of PSD.',
 'Mathlib/Order/ConditionallyCompletePartialOrder/Basic.lean':
   'IsLeast.csInf_eq generated by to_dual from IsGreatest.csSup_eq; uses least-element membership and bounds.',
 'Mathlib/LinearAlgebra/Matrix/ConjTranspose.lean':
   'Reuse inspection: existing conjugate transpose of vecMulVec.',
 'Mathlib/Data/Matrix/Mul.lean':
   'Reuse inspection: existing vecMulVec multiplication and scalar movement.'}
apis = {}
for rel, purpose in api_files.items():
    apis[rel] = {'sha256': sha(mathlib/rel), 'purpose': purpose,
      'url': 'https://github.com/leanprover-community/mathlib4/blob/0df444a360eaa60ab8c11dca51a86af692955474/'+rel}
rel = 'LeanCert/Tactic/Verification.lean'
apis[rel] = {'sha256': sha(leancert/rel),
 'purpose': 'Explicit kernel trust audit examines collected axioms and rejects sorry/custom/native execution trust. No numerical interval certificate is claimed.',
 'url': 'https://github.com/alerad/leancert/blob/621a43d7cf21f87872392a01e874f2f1dbddc926/'+rel}
save('api-source-inputs.json', {'actual_consumption': 'actual-dependencies.json',
 'source_pins_checked_clean': 'dependency-pins.json', 'files': apis})

diagnostic = PROJECT/'reviews/statement-referee-2-evidence/reconstruct.py'
fresh_diagnostic = OUT/'reconstruct.py'
shutil.copyfile(diagnostic, fresh_diagnostic)
assert sha(diagnostic) == sha(fresh_diagnostic)
cp = subprocess.run(['python3',str(fresh_diagnostic)], cwd=PROJECT,
                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
(OUT/'reconstruction.log').write_bytes(cp.stdout)
assert cp.returncode == 0
save('reconstruction-run.json', {'exit_code': cp.returncode,
 'script_sha256': sha(fresh_diagnostic), 'log_sha256': sha(OUT/'reconstruction.log'),
 'result_sha256': sha(OUT/'reconstruction.json'),
 'attribution': 'Fresh rerun of this independent reviewer\'s prior statement diagnostic.',
 'scope': 'Finite exact Q(sqrt(3),i) checks supplement, and do not prove, the all-k theorem.'})

freeze = json.loads((PROJECT/'reviews/proof-freeze.json').read_text())
for rel, entry in freeze['files'].items():
    assert sha(PROJECT/rel) == entry['sha256']
    assert (PROJECT/rel).stat().st_size == entry['bytes']
print('PASS: ten pinned rubrics, fourteen actual/reuse API source files, fresh exact diagnostics; all 101 frozen project files unchanged.')
