import NLA.TR06.ProjectionAtlas
set_option leancert.trust "kernel"
#print axioms NLA.TR06.Area.Proposed.coordProjection
#assert_trust kernel NLA.TR06.Area.Proposed.coordProjection
#print axioms NLA.TR06.Area.Proposed.HasSmoothEmbeddedCharts
#assert_trust kernel NLA.TR06.Area.Proposed.HasSmoothEmbeddedCharts
#print axioms NLA.TR06.Area.Proposed.ProjectionLocallyInjectiveSet
#assert_trust kernel NLA.TR06.Area.Proposed.ProjectionLocallyInjectiveSet
#print axioms NLA.TR06.Area.Proposed.UniformProjectionAtlasStatement
#assert_trust kernel NLA.TR06.Area.Proposed.UniformProjectionAtlasStatement
#print axioms NLA.TR06.Area.Proposed.matrix_exists_injective_row_restriction
#assert_trust kernel NLA.TR06.Area.Proposed.matrix_exists_injective_row_restriction
#print axioms NLA.TR06.Area.Proposed.coordProjectionL
#assert_trust kernel NLA.TR06.Area.Proposed.coordProjectionL
#print axioms NLA.TR06.Area.Proposed.coordProjectionL_apply
#assert_trust kernel NLA.TR06.Area.Proposed.coordProjectionL_apply
#print axioms NLA.TR06.Area.Proposed.exists_injective_coordinate_projection
#assert_trust kernel NLA.TR06.Area.Proposed.exists_injective_coordinate_projection
#print axioms NLA.TR06.Area.Proposed.isometricOperators
#assert_trust kernel NLA.TR06.Area.Proposed.isometricOperators
#print axioms NLA.TR06.Area.Proposed.isCompact_isometricOperators
#assert_trust kernel NLA.TR06.Area.Proposed.isCompact_isometricOperators
#print axioms NLA.TR06.Area.Proposed.exists_coordinate_bound_neighborhood
#assert_trust kernel NLA.TR06.Area.Proposed.exists_coordinate_bound_neighborhood
#print axioms NLA.TR06.Area.Proposed.uniform_isometric_coordinate_bound
#assert_trust kernel NLA.TR06.Area.Proposed.uniform_isometric_coordinate_bound
#print axioms NLA.TR06.Area.Proposed.uniform_tangent_coordinate_bound
#assert_trust kernel NLA.TR06.Area.Proposed.uniform_tangent_coordinate_bound
#print axioms NLA.TR06.Area.Proposed.tangent_coordinate_equiv
#assert_trust kernel NLA.TR06.Area.Proposed.tangent_coordinate_equiv
#print axioms NLA.TR06.Area.Proposed.projection_chart_locally_injective
#assert_trust kernel NLA.TR06.Area.Proposed.projection_chart_locally_injective
#print axioms NLA.TR06.Area.Proposed.local_projection_charts
#assert_trust kernel NLA.TR06.Area.Proposed.local_projection_charts
#print axioms NLA.TR06.Area.Proposed.zero_dimensional_charts_countable
#assert_trust kernel NLA.TR06.Area.Proposed.zero_dimensional_charts_countable
#print axioms NLA.TR06.Area.Proposed.uniform_projection_atlas
#assert_trust kernel NLA.TR06.Area.Proposed.uniform_projection_atlas
