import NLA.FR05.Proof

#print axioms NLA.FR05.otherRowSpan_eq_span_subtype
#print axioms NLA.FR05.exists_unit_otherRowNormal
#print axioms NLA.FR05.rowNearSpan
#print axioms NLA.FR05.isOpen_rowNearSpan
#print axioms NLA.FR05.rowSpanDistanceBad_implies_rowNearSpan
#print axioms NLA.FR05.rowNearSpan_inner_lt
#print axioms NLA.FR05.rowSampleSplit
#print axioms NLA.FR05.measurePreserving_rowSampleSplit
#print axioms NLA.FR05.rowSampleSplit_symm_self
#print axioms NLA.FR05.rowSampleSplit_symm_other
#print axioms NLA.FR05.iid_rowNearSpan_le
#print axioms NLA.FR05.iid_rowNearSpan_reindex_le
#print axioms NLA.FR05.measurable_sourceJacobianRow
#print axioms NLA.FR05.sourceJacobianRow_inner
#print axioms NLA.FR05.iidSourceCoordinateLaw_rowNearSpan_le
#print axioms NLA.FR05.iidSourceCoordinateLaw_leastGain_failure_le
#print axioms NLA.FR05.source_smallBall_calibration
#print axioms NLA.FR05.source_row_threshold_le
#print axioms NLA.FR05.source_smallBall_bound_calibrated
#print axioms NLA.FR05.sourceJacobian_leastGain_failure_le
#print axioms NLA.FR05.SourceNewtonGood
#print axioms NLA.FR05.sourceNewtonGood_failure_le
#print axioms NLA.FR05.sourceNewtonGood_failure_order
#print axioms NLA.FR05.exists_zero_of_local_linear_control
#print axioms NLA.FR05.sourceFactorDecode
#print axioms NLA.FR05.sourceFactorDecode_direction_le
#print axioms NLA.FR05.abs_plantedEquationQuadratic_le
#print axioms NLA.FR05.sourceEquationEuclidean
#print axioms NLA.FR05.sourceEquation_difference_identity
#print axioms NLA.FR05.source_sqrt_card_le_two_mul
#print axioms NLA.FR05.sourceEquation_nonlinear_difference_le
#print axioms NLA.FR05.sourceJacobianPerturbationScale_le
#print axioms NLA.FR05.sourceEquation_frozen_difference_le
#print axioms NLA.FR05.sourceEquation_seed_le
#print axioms NLA.FR05.sourceNewtonRadius
#print axioms NLA.FR05.sourceNewton_calibration
#print axioms NLA.FR05.isClosed_globallyPhased
#print axioms NLA.FR05.measurableSet_phaseRetrievalInjective
#print axioms NLA.FR05.sourceNewtonGood_not_injective
#print axioms NLA.FR05.sourcePlantedFrameLaw_injective_le_bad
#print axioms NLA.FR05.proposition_3_1
#print axioms NLA.FR05.phaseRetrievalInjective_mul_unitary
#print axioms NLA.FR05.sourceHaarPlantedFrameLawAt
#print axioms NLA.FR05.sourceHaarPlantedFrameLaw_injective_eq
#print axioms NLA.FR05.proposition_3_1_haar
#print axioms NLA.FR05.proposition_3_2
