/- Frozen statement boundary. Changes reopen independent review. -/
import Mathlib
import NLA.Statements.Infrastructure
import LeanCert.Tactic.Verification

/-! TR-26: reduced degrees of the isotropic and nonisotropic Rayleigh–Ritz
discriminant parts for the fixed, unweighted rational normal curve. The
projective incidence is represented by its separately scaling-invariant
nonzero affine cone. Its Zariski closure is defined by all vanishing
polynomials; the Jacobian uses their full ideal, and reduced projective
degree uses a squarefree homogeneous defining polynomial. This is a
statement, not a proof of the source's degree calculations. -/
set_option autoImplicit false
set_option leancert.trust "kernel"

open scoped BigOperators
open Classical

namespace NLA.ReviewedStatements.TR26

abbrev Index (d : ℕ) := Fin (d + 1)

/-- Independent coordinates of a complex symmetric `(d+1)×(d+1)` matrix.
Using only the upper triangle ensures polynomial degree is computed in the
actual symmetric-matrix parameter space. -/
abbrev SymIndex (d : ℕ) :=
  {ij : Index d × Index d // ij.1 ≤ ij.2}

abbrev Parameter (d : ℕ) := SymIndex d → ℂ
abbrev CurveVector (d : ℕ) := Index d → ℂ
abbrev ParameterRing (d : ℕ) := MvPolynomial (SymIndex d) ℂ
abbrev IncidenceVariable (d : ℕ) := Sum (Index d) (SymIndex d)
abbrev IncidenceRing (d : ℕ) := MvPolynomial (IncidenceVariable d) ℂ

/-- The symmetric entry represented by upper-triangle coordinates. -/
def symmetricEntry {d : ℕ} (H : Parameter d) (i j : Index d) : ℂ :=
  if h : i ≤ j then H ⟨(i, j), h⟩
  else H ⟨(j, i), le_of_lt (lt_of_not_ge h)⟩

/-- The fixed unweighted Veronese coordinates
`[a^d : a^(d-1)b : ⋯ : b^d]`, including `a=0` (infinity). -/
def veronese (d : ℕ) (a b : ℂ) : CurveVector d :=
  fun i => a ^ (d - i.val) * b ^ i.val

/-- Its two ordinary polynomial partial derivatives. Natural subtraction
is harmless at an exponent zero because its coefficient is then zero. -/
def veroneseDa (d : ℕ) (a b : ℂ) : CurveVector d :=
  fun i => (d - i.val : ℕ) * a ^ (d - i.val - 1) * b ^ i.val

def veroneseDb (d : ℕ) (a b : ℂ) : CurveVector d :=
  fun i => (i.val : ℂ) * a ^ (d - i.val) * b ^ (i.val - 1)

/-- Nonzero points of the affine cone over the exact projective curve.
The separate scalar accounts for every projective representative. -/
def OnCurve {d : ℕ} (z : CurveVector d) : Prop :=
  ∃ a b c : ℂ, (a ≠ 0 ∨ b ≠ 0) ∧ c ≠ 0 ∧
    ∀ i : Index d, z i = c * veronese d a b i

/-- All transpose pairings are complex bilinear, with no conjugation. -/
def denominator {d : ℕ} (z : CurveVector d) : ℂ :=
  ∑ i : Index d, z i * z i

def numerator {d : ℕ} (H : Parameter d) (z : CurveVector d) : ℂ :=
  ∑ i : Index d, ∑ j : Index d, z i * symmetricEntry H i j * z j

def denominatorDerivative {d : ℕ} (z v : CurveVector d) : ℂ :=
  ∑ i : Index d, (v i * z i + z i * v i)

def numeratorDerivative {d : ℕ} (H : Parameter d)
    (z v : CurveVector d) : ℂ :=
  ∑ i : Index d, ∑ j : Index d,
    (v i * symmetricEntry H i j * z j +
      z i * symmetricEntry H i j * v j)

/-- Numerator of the directional derivative of the rational Rayleigh
quotient, valid exactly when `denominator z ≠ 0`. -/
def quotientDerivativeNumerator {d : ℕ} (H : Parameter d)
    (z v : CurveVector d) : ℂ :=
  numeratorDerivative H z v * denominator z -
    numerator H z * denominatorDerivative z v

/-- The nonisotropic critical-point incidence before Zariski closure.
Both parameter directions are tested, so the full tangent to the
projective curve is represented, including its point at infinity. -/
def OpenCritical {d : ℕ} (z : CurveVector d) (H : Parameter d) : Prop :=
  H ≠ 0 ∧ ∃ a b c : ℂ,
    (a ≠ 0 ∨ b ≠ 0) ∧ c ≠ 0 ∧
    (∀ i : Index d, z i = c * veronese d a b i) ∧
    denominator (veronese d a b) ≠ 0 ∧
    quotientDerivativeNumerator H (veronese d a b) (veroneseDa d a b) = 0 ∧
    quotientDerivativeNumerator H (veronese d a b) (veroneseDb d a b) = 0

def incidenceCoordinates {d : ℕ} (z : CurveVector d) (H : Parameter d) :
    IncidenceVariable d → ℂ
  | .inl i => z i
  | .inr ij => H ij

/-- The full polynomial vanishing ideal of the open projective incidence,
expressed on its affine cone. This is a concrete set of polynomials, not a
chosen list of convenient critical equations. -/
def VanishesOnOpen (d : ℕ) (f : IncidenceRing d) : Prop :=
  ∀ (z : CurveVector d) (H : Parameter d),
    OpenCritical z H → MvPolynomial.eval (incidenceCoordinates z H) f = 0

/-- The Zariski closure in the product of projective spaces, represented
by the common zeros of the entire cone vanishing ideal at nonzero points. -/
def Incidence (d : ℕ) (z : CurveVector d) (H : Parameter d) : Prop :=
  z ≠ 0 ∧ H ≠ 0 ∧ OnCurve z ∧
    ∀ f : IncidenceRing d, VanishesOnOpen d f →
      MvPolynomial.eval (incidenceCoordinates z H) f = 0

/-- The conormal space generated by the `z`-partial derivatives of *every*
polynomial in the full incidence ideal. Its dimension is the generator-
independent Jacobian rank used in the canonical problem. -/
noncomputable def JacobianSpace (d : ℕ) (z : CurveVector d)
    (H : Parameter d) : Submodule ℂ (CurveVector d) :=
  Submodule.span ℂ
    {v | ∃ f : IncidenceRing d, VanishesOnOpen d f ∧
      v = fun j : Index d =>
        MvPolynomial.eval (incidenceCoordinates z H)
          (MvPolynomial.pderiv (.inl j) f)}

def Ramification (d : ℕ) (z : CurveVector d) (H : Parameter d) : Prop :=
  Incidence d z H ∧ Module.finrank ℂ (JacobianSpace d z H) ≤ d - 1

/-- The exact projected isotropic part; the source does not insert a new
closure after this projection. -/
def IsotropicImage (d : ℕ) : Set (Parameter d) :=
  {H | ∃ z : CurveVector d, Ramification d z H ∧ denominator z = 0}

def NonisotropicImage (d : ℕ) : Set (Parameter d) :=
  {H | ∃ z : CurveVector d, Ramification d z H ∧ denominator z ≠ 0}

/-- Zariski closure of the nonisotropic projection in the actual
projective symmetric-matrix parameter space. -/
def NonisotropicClosure (d : ℕ) : Set (Parameter d) :=
  {H | H ≠ 0 ∧ ∀ P : ParameterRing d,
    (∀ H' ∈ NonisotropicImage d, MvPolynomial.eval H' P = 0) →
      MvPolynomial.eval H P = 0}

/-- An exact reduced projective hypersurface of degree `degree`. A
nonzero squarefree homogeneous equation in the independent symmetric
coordinates cuts out exactly the set of nonzero projective parameters;
its total degree is the reduced projective degree. -/
def HasReducedDegree (d degree : ℕ) (S : Set (Parameter d)) : Prop :=
  ∃ P : ParameterRing d,
    P ≠ 0 ∧ Squarefree P ∧ P.IsHomogeneous degree ∧
      ∀ H : Parameter d, H ≠ 0 →
        (H ∈ S ↔ MvPolynomial.eval H P = 0)

/-- Both exact all-order reduced-degree formulas, including `d=2`. -/
def Target : Prop :=
  ∀ d : ℕ, 2 ≤ d →
    HasReducedDegree d (6 * (d - 1)) (NonisotropicClosure d) ∧
    HasReducedDegree d (2 * d) (IsotropicImage d)

#assert_statement Target
#assert_trust kernel Target
#print axioms Target

end NLA.ReviewedStatements.TR26
