#!/usr/bin/env python3
"""Second exact certificate implementation (no NumPy, no float eigensolver).

Uses the direct binomial formula for every shifted coefficient, rather than the
Horner-shift algorithm in spread_exact.py. It checks root bounds, not exhaustive
pattern coverage. Run the main verifier as well. Authored in the same audit;
not an independent researcher/agent review or a formal proof.
"""
from __future__ import annotations
import argparse, hashlib, json
from math import comb
from pathlib import Path
from collections import Counter

def integer(x):
    if type(x) is not int:
        raise ValueError('Expected a JSON integer, not a bool or float.')
    return x

def all_shifted_coefficients_nonnegative(c,h,q):
    n=len(c)-1
    hp=[1];qp=[1]
    for _ in range(n):hp.append(hp[-1]*h);qp.append(qp[-1]*q)
    # [z^k] q^n p((z+h)/q)
    for k in range(n+1):
        value=sum(c[i]*comb(n-i,k)*hp[n-i-k]*qp[i] for i in range(n-k+1))
        if value<0:return False
    return True

def check(path):
    data=json.loads(Path(path).read_text())
    n,lo,hi,F=map(integer,(data['n'],data['low'],data['high'],data['maximum_spread_squared']))
    if (n,lo,hi,F) not in {(8,1,2,292),(10,0,1,133),(11,0,1,161)}:
        raise ValueError('Not one of this pack\'s three claimed cases.')
    if data['schema']!='spread-exact-v1' or data['failures'] or data['claim']!='EXACT_FINITE_CASE':
        raise ValueError('Invalid/unfinished certificate file.')
    total=1<<(2*n-1)
    if integer(data['pattern_count'])!=total:raise ValueError('Pattern-count metadata.')
    seen=set();counts=Counter()
    for item in data['certificates']:
        c=tuple(map(integer,item['coefficients']))
        if len(c)!=n+1 or c[0]!=1 or c in seen:raise ValueError('Polynomial format/duplicate.')
        seen.add(c)
        if not 0<=integer(item['pattern'])<total:raise ValueError('Representative index.')
        kind=item['kind'];counts[kind]+=1
        if kind=='rank_two':
            if c[2]>=0 or any(c[3:]):raise ValueError('Not two opposite nonzero roots.')
            g=c[1]*c[1]-4*c[2]
            if g>F or integer(item['gap_squared'])!=g:raise ValueError('Quadratic bound.')
        elif kind=='rational_enclosure':
            h,j,q=map(integer,(item['upper'],item['negative_upper'],item['q']))
            if q<=0 or h+j<0 or (h+j)**2>F*q*q:raise ValueError('Width bound.')
            if not all_shifted_coefficients_nonnegative(c,h,q):raise ValueError('Positive-side root bound.')
            minus=tuple(ci if i%2==0 else -ci for i,ci in enumerate(c))
            if not all_shifted_coefficients_nonnegative(minus,j,q):raise ValueError('Negative-side root bound.')
        else:raise ValueError('Certificate kind.')
    if len(seen)!=integer(data['distinct_polynomial_count']):raise ValueError('Count.')
    if dict(counts)!=data['certificate_counts']:raise ValueError('Type counts.')
    h=hashlib.sha256()
    for c in sorted(seen):h.update((','.join(map(str,c))+'\n').encode())
    if h.hexdigest()!=data['polynomial_sha256']:raise ValueError('Polynomial integrity digest.')
    # Sanity-check sign discrimination of this alternate formula.
    if not all_shifted_coefficients_nonnegative((1,0,-1),1,1):raise ArithmeticError('Sanity positive.')
    if all_shifted_coefficients_nonnegative((1,0,-1),0,1):raise ArithmeticError('Sanity negative.')
    print(f'PASS: direct-binomial integer checks of all {len(seen)} root certificates for n={n}, bounds squared={F}. Coverage NOT regenerated by this secondary checker.',flush=True)

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('files',nargs='+')
    for p in ap.parse_args().files:check(p)
if __name__=='__main__':main()
