import NLA.TR06.Complexification
import NLA.TR06.ClosedFibers
set_option leancert.trust "kernel"
#print axioms NLA.TR06.complexify
#assert_trust kernel NLA.TR06.complexify
#print axioms NLA.TR06.complexify_apply
#assert_trust kernel NLA.TR06.complexify_apply
#print axioms NLA.TR06.complexify_injective
#assert_trust kernel NLA.TR06.complexify_injective
#print axioms NLA.TR06.complexify_zero
#assert_trust kernel NLA.TR06.complexify_zero
#print axioms NLA.TR06.complexify_add
#assert_trust kernel NLA.TR06.complexify_add
#print axioms NLA.TR06.complexify_sum
#assert_trust kernel NLA.TR06.complexify_sum
#print axioms NLA.TR06.complexify_pureTensor
#assert_trust kernel NLA.TR06.complexify_pureTensor
#print axioms NLA.TR06.complexify_rankOne
#assert_trust kernel NLA.TR06.complexify_rankOne
#print axioms NLA.TR06.complexify_decomposes
#assert_trust kernel NLA.TR06.complexify_decomposes
#print axioms NLA.TR06.exactRank_of_complexify
#assert_trust kernel NLA.TR06.exactRank_of_complexify
#print axioms NLA.TR06.identifiable_of_complexify
#assert_trust kernel NLA.TR06.identifiable_of_complexify
#print axioms NLA.TR06.exact_identifiable_of_complexify
#assert_trust kernel NLA.TR06.exact_identifiable_of_complexify
#print axioms NLA.TR06.rankAtMostOne
#assert_trust kernel NLA.TR06.rankAtMostOne
#print axioms NLA.TR06.closedRankOneProduct
#assert_trust kernel NLA.TR06.closedRankOneProduct
#print axioms NLA.TR06.closedAdditionFiber
#assert_trust kernel NLA.TR06.closedAdditionFiber
#print axioms NLA.TR06.exists_decomposes_remove_zeros
#assert_trust kernel NLA.TR06.exists_decomposes_remove_zeros
#print axioms NLA.TR06.rankOne_of_mem_closedAdditionFiber
#assert_trust kernel NLA.TR06.rankOne_of_mem_closedAdditionFiber
#print axioms NLA.TR06.closedAdditionFiber_finite_nonempty
#assert_trust kernel NLA.TR06.closedAdditionFiber_finite_nonempty
