/-
Proposed exact character-fiber correspondence and quasi-finite bridge.
No proof of these propositions is supplied in this boundary file.
Formalization: George Stepaniants, Department of Computing and Mathematical
Sciences, California Institute of Technology.
-/
import Mathlib.RingTheory.ZariskisMainTheorem
import Mathlib.RingTheory.Nullstellensatz
import LeanCert.Tactic.Verification

set_option autoImplicit false
noncomputable section
universe u v w

namespace NLA.TR06.Proposed

variable {K : Type u} {R : Type v} {S : Type w}
  [CommRing K] [CommRing R] [CommRing S]
  [Algebra K R] [Algebra K S] [Algebra R S] [IsScalarTower K R S]

/-- The ideal in S generated by the kernel of the specified base character. -/
def characterFiberIdeal (χ : R →ₐ[K] K) : Ideal S :=
  (RingHom.ker χ.toRingHom).map (algebraMap R S)

/-- Actual K-valued characters on S lying above one fixed character on R. -/
def characterFiber (χ : R →ₐ[K] K) : Set (S →ₐ[K] K) :=
  {f | f.comp (IsScalarTower.toAlgHom K R S) = χ}

/-- The quotient universal property gives the actual character correspondence,
with the map prescribed as precomposition by the quotient homomorphism. -/
def QuotientCharacterCorrespondenceStatement : Prop :=
  ∀ (K : Type u) (R : Type v) (S : Type w) [CommRing K] [CommRing R] [CommRing S]
    [Algebra K R] [Algebra K S] [Algebra R S] [IsScalarTower K R S]
    (χ : R →ₐ[K] K),
    Set.BijOn
      (fun f : (S ⧸ characterFiberIdeal (S := S) χ) →ₐ[K] K =>
        f.comp (Ideal.Quotient.mkₐ K (characterFiberIdeal (S := S) χ)))
      Set.univ (characterFiber (S := S) χ)

/-- A finite character fiber makes the original R-algebra quasi-finite at every
character kernel in that fiber. No source-domain hypothesis is required here. -/
def QuasiFiniteAtOfFiniteCharacterFiberStatement : Prop :=
  ∀ (K : Type u) (R : Type v) (S : Type w) [Field K] [IsAlgClosed K]
    [CommRing R] [CommRing S]
    [Algebra K R] [Algebra K S] [Algebra R S] [IsScalarTower K R S]
    [Algebra.FiniteType K S] (χ : R →ₐ[K] K),
    (characterFiber (S := S) χ).Finite →
    ∀ f : S →ₐ[K] K, f ∈ characterFiber (S := S) χ →
      letI : (RingHom.ker f.toRingHom).IsPrime := RingHom.ker_isPrime f.toRingHom
      Algebra.QuasiFiniteAt R (RingHom.ker f.toRingHom)

/-- For an integral source, one finite nonempty actual character fiber implies
quasi-finiteness at the source generic point. Empty fibers do not suffice. -/
def GenericQuasiFiniteOfFiniteNonemptyCharacterFiberStatement : Prop :=
  ∀ (K : Type u) (R : Type v) (S : Type w) [Field K] [IsAlgClosed K]
    [CommRing R] [CommRing S] [IsDomain S]
    [Algebra K R] [Algebra K S] [Algebra R S] [IsScalarTower K R S]
    [Algebra.FiniteType K S] (χ : R →ₐ[K] K),
    (characterFiber (S := S) χ).Finite →
    (characterFiber (S := S) χ).Nonempty →
    Algebra.QuasiFiniteAt R (⊥ : Ideal S)

#check QuotientCharacterCorrespondenceStatement
#check QuasiFiniteAtOfFiniteCharacterFiberStatement
#check GenericQuasiFiniteOfFiniteNonemptyCharacterFiberStatement

end NLA.TR06.Proposed
