/-
Copyright (c) 2026 George Stepaniants. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: George Stepaniants

Department of Computing and Mathematical Sciences, California Institute of
Technology. Original TR-06 mathematical proof: Matthew J. Colbrook.
-/
import NLA.TR06.SegreAlgebraDefinitions
import NLA.TR06.ClosedCone
import LeanCert.Tactic.Verification

set_option autoImplicit false
set_option leancert.trust "kernel"
noncomputable section
open scoped BigOperators
open Set
namespace NLA.TR06.Proposed

variable {d : ℕ} {n : Fin d → ℕ} {r : ℕ}

theorem segre_algebra_structure : SegreAlgebraStructureStatement := by
  intro d n r
  constructor
  · infer_instance
  · exact Algebra.FiniteType.adjoin_of_finite (Set.finite_range _)

/-- Every character is determined by its actual ordered tensor coordinates. -/
theorem characterTuple_injective :
    Function.Injective (characterTuple (d := d) (n := n) (r := r)) := by
  intro f g hfg
  apply AlgHom.adjoin_ext
  rintro p ⟨⟨i, q⟩, rfl⟩
  exact congrArg (fun a : Fin r → Tensor ℂ d n => a i q) hfg

/-- Character extraction commutes exactly with actual tensor addition. -/
theorem character_comp_addition (f : SegreSource d n r →ₐ[ℂ] ℂ) :
    f.comp (additionAlgebraHom d n r) =
      MvPolynomial.aeval (fun q => (∑ i, characterTuple f i) q) := by
  ext q
  simp [additionAlgebraHom, characterTuple]

/-- Restricting a raw-factor evaluation gives an actual source character. -/
def factorCharacter (u : Fin r → (j : Fin d) → Fin (n j) → ℂ) :
    SegreSource d n r →ₐ[ℂ] ℂ :=
  (MvPolynomial.aeval (fun x : OrderedFactorIndex d n r => u x.1 x.2.1 x.2.2)).comp
    (segreSourceSubalgebra d n r).val

theorem characterTuple_factorCharacter
    (u : Fin r → (j : Fin d) → Fin (n j) → ℂ) :
    characterTuple (factorCharacter u) = fun i => pureTensor (u i) := by
  funext i
  ext q
  simp [characterTuple, factorCharacter, segreCoordinate, segreCoordinatePolynomial, pureTensor]

/-- Genuine polynomial relations inside the source subalgebra; no assertion
about the ideal generated by these relations is used. -/
theorem segreCoordinate_pivot_identity (i : Fin r) (p q : TensorIndex d n) :
    segreCoordinate (i, q) * segreCoordinate (i, p) ^ (d - 1) =
      ∏ j : Fin d, segreCoordinate (i, Function.update p j (q j)) := by
  apply Subtype.ext
  change (segreSourceSubalgebra d n r).val
      (segreCoordinate (i, q) * segreCoordinate (i, p) ^ (d - 1)) =
    (segreSourceSubalgebra d n r).val
      (∏ j : Fin d, segreCoordinate (i, Function.update p j (q j)))
  rw [map_mul, map_pow, map_prod]
  change segreCoordinatePolynomial (i, q) * segreCoordinatePolynomial (i, p) ^ (d - 1) =
    ∏ j : Fin d, segreCoordinatePolynomial (i, Function.update p j (q j))
  unfold segreCoordinatePolynomial
  have h := prod_prod_diagonal_identity
    (fun j : Fin d => (MvPolynomial.X (i, ⟨j, q j⟩) : MvPolynomial (OrderedFactorIndex d n r) ℂ))
    (fun j : Fin d => (MvPolynomial.X (i, ⟨j, p j⟩) : MvPolynomial (OrderedFactorIndex d n r) ℂ))
  simp only [Fintype.card_fin] at h
  rw [h]
  apply Finset.prod_congr rfl
  intro j _
  apply Finset.prod_congr rfl
  intro k _
  by_cases hkj : k = j
  · subst k
    simp
  · simp [hkj]

/-- Every source character yields actual zero-or-rank-one tensor summands. -/
theorem characterTuple_mem_closedProduct (hd : 0 < d)
    (f : SegreSource d n r →ₐ[ℂ] ℂ) :
    characterTuple f ∈ closedRankOneProduct ℂ d n r := by
  intro i
  apply (rankAtMostOne_iff_pivot_equations hd (characterTuple f i)).mpr
  intro p q
  change f (segreCoordinate (i, q)) * f (segreCoordinate (i, p)) ^ (d - 1) =
    ∏ j : Fin d, f (segreCoordinate (i, Function.update p j (q j)))
  simpa only [map_mul, map_pow, map_prod] using
    congrArg f (segreCoordinate_pivot_identity i p q)

/-- Every actual full closed-product tuple is realized by a source character. -/
theorem range_characterTuple (hd : 0 < d) :
    Set.range (characterTuple (d := d) (n := n) (r := r)) =
      closedRankOneProduct ℂ d n r := by
  ext a
  constructor
  · rintro ⟨f, rfl⟩
    exact characterTuple_mem_closedProduct hd f
  · intro ha
    have hfactor (i : Fin r) : ∃ u : (j : Fin d) → Fin (n j) → ℂ, pureTensor u = a i := by
      change a i ∈ Set.range (pureTensor : ((j : Fin d) → Fin (n j) → ℂ) → Tensor ℂ d n)
      rw [range_pureTensor_eq_rankAtMostOne hd]
      exact ha i
    choose u hu using hfactor
    refine ⟨factorCharacter u, ?_⟩
    rw [characterTuple_factorCharacter]
    exact funext hu

/-- Exact character/actual-tuple correspondence, with addition compatibility. -/
theorem segre_characters : SegreCharactersStatement := by
  intro d n r hd
  exact ⟨characterTuple_injective, range_characterTuple hd, character_comp_addition⟩

#print axioms segre_algebra_structure
#print axioms characterTuple_injective
#print axioms character_comp_addition
#print axioms characterTuple_factorCharacter
#assert_trust kernel segre_algebra_structure
#assert_trust kernel characterTuple_injective
#assert_trust kernel character_comp_addition
#assert_trust kernel characterTuple_factorCharacter
#print axioms segreCoordinate_pivot_identity
#print axioms characterTuple_mem_closedProduct
#print axioms range_characterTuple
#print axioms segre_characters
#assert_trust kernel segreCoordinate_pivot_identity
#assert_trust kernel characterTuple_mem_closedProduct
#assert_trust kernel range_characterTuple
#assert_trust kernel segre_characters
end NLA.TR06.Proposed
